### PR TITLE
Use allowSpaces from github hash of tributejs

### PR DESCRIPTION
**Pull request by imontiel**
Waiting on https://github.com/zurb/tribute/pull/41 so that Yarn won't throw a fit when trying to install a specific commit from Github.

### CODE REVIEW

**Comment by imontiel** [comment]
Still waiting for ^2.1.1 to be released: https://github.com/zurb/tribute/releases

**Comment by mrsweaters** [comment]
@imontiel Hey! Is this still an issue on our end?

**Comment by imontiel** [comment]
Nope, I can probably safely bump the peer version and release it! `^2.2.0` will be the peerDependency.

**Comment by imontiel** [comment]
Nevermind just the dependency for developing this package needs to be updated, not the peer dependency.

**Pull request merged**
